#!/bin/bash
set -e

echo "=============================================="
echo "Tsugi Docker Container Starting..."
echo "=============================================="

# =============================================================================
# MariaDB Initialization
# =============================================================================

initialize_mariadb() {
    echo "Initializing MariaDB..."

    # Start MariaDB service
    service mariadb start

    # Wait for MariaDB to be ready
    echo "Waiting for MariaDB to be ready..."
    for i in {1..30}; do
        if mysqladmin ping -h localhost --silent; then
            echo "MariaDB is ready!"
            break
        fi
        echo "Waiting for MariaDB... ($i/30)"
        sleep 1
    done

    # Check if database exists, if not create it
    if ! mysql -u root -e "USE ${TSUGI_DB_NAME}" 2>/dev/null; then
        echo "Creating Tsugi database and user..."
        mysql -u root <<-EOSQL
            CREATE DATABASE IF NOT EXISTS ${TSUGI_DB_NAME} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            CREATE USER IF NOT EXISTS '${TSUGI_DB_USER}'@'localhost' IDENTIFIED BY '${TSUGI_DB_PASSWORD}';
            CREATE USER IF NOT EXISTS '${TSUGI_DB_USER}'@'127.0.0.1' IDENTIFIED BY '${TSUGI_DB_PASSWORD}';
            CREATE USER IF NOT EXISTS '${TSUGI_DB_USER}'@'%' IDENTIFIED BY '${TSUGI_DB_PASSWORD}';
            GRANT ALL PRIVILEGES ON ${TSUGI_DB_NAME}.* TO '${TSUGI_DB_USER}'@'localhost';
            GRANT ALL PRIVILEGES ON ${TSUGI_DB_NAME}.* TO '${TSUGI_DB_USER}'@'127.0.0.1';
            GRANT ALL PRIVILEGES ON ${TSUGI_DB_NAME}.* TO '${TSUGI_DB_USER}'@'%';
            FLUSH PRIVILEGES;
EOSQL
        echo "Database and user created successfully!"
    else
        echo "Database ${TSUGI_DB_NAME} already exists."
    fi
}

# =============================================================================
# Tsugi Configuration
# =============================================================================

configure_tsugi() {
    CONFIG_FILE="/var/www/html/tsugi/config.php"

    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Generating Tsugi config.php..."

        # Generate random secrets if defaults are used
        if [ "$TSUGI_COOKIE_SECRET" = "change-me-cookie-secret-1234567890" ]; then
            TSUGI_COOKIE_SECRET=$(openssl rand -hex 32)
        fi
        if [ "$TSUGI_SESSION_SALT" = "change-me-session-salt-1234567890" ]; then
            TSUGI_SESSION_SALT=$(openssl rand -hex 32)
        fi
        if [ "$TSUGI_MAIL_SECRET" = "change-me-mail-secret-1234567890" ]; then
            TSUGI_MAIL_SECRET=$(openssl rand -hex 32)
        fi

        # Hash admin password if it's not already a SHA256 hash (64 hex chars)
        if [[ ! "$TSUGI_ADMIN_PASSWORD" =~ ^[a-fA-F0-9]{64}$ ]]; then
            TSUGI_ADMIN_PASSWORD_HASH=$(echo -n "$TSUGI_ADMIN_PASSWORD" | sha256sum | cut -d' ' -f1)
        else
            TSUGI_ADMIN_PASSWORD_HASH="$TSUGI_ADMIN_PASSWORD"
        fi

        cat > "$CONFIG_FILE" <<EOPHP
<?php
/**
 * Tsugi Configuration File
 * Generated by Docker entrypoint script
 */

\$CFG = new \stdClass();

// Database configuration
\$CFG->pdo = 'mysql:host=${TSUGI_DB_HOST};port=${TSUGI_DB_PORT};dbname=${TSUGI_DB_NAME}';
\$CFG->dbuser = '${TSUGI_DB_USER}';
\$CFG->dbpass = '${TSUGI_DB_PASSWORD}';
\$CFG->dbprefix = '';

// Application URL configuration
\$CFG->wwwroot = '${TSUGI_WWWROOT}';
\$CFG->apphome = false;

// Service name
\$CFG->servicename = '${TSUGI_SERVICENAME}';

// Admin password (SHA256 hash)
\$CFG->adminpw = '${TSUGI_ADMIN_PASSWORD_HASH}';

// Developer mode (enables test harness)
\$CFG->DEVELOPER = ${TSUGI_DEVELOPER_MODE};

// Security secrets
\$CFG->cookiesecret = '${TSUGI_COOKIE_SECRET}';
\$CFG->sessionsalt = '${TSUGI_SESSION_SALT}';
\$CFG->mailsecret = '${TSUGI_MAIL_SECRET}';

// Timezone
\$CFG->timezone = '${TSUGI_TIMEZONE}';

// Data storage
\$CFG->dataroot = '/tsugi-data/blobs';

// Git command location
\$CFG->git_command = '/usr/bin/git';

// Tool folders
\$CFG->tool_folders = array("admin", "mod");
\$CFG->install_folder = \$CFG->dirroot.'/mod';

// Optional: Google services (uncomment and configure if needed)
// \$CFG->google_client_id = '';
// \$CFG->google_client_secret = '';
// \$CFG->google_map_api_key = '';

// Data retention settings (days, 0 = never expire)
\$CFG->expire_pii_days = 0;
\$CFG->expire_user_days = 0;
\$CFG->expire_context_days = 0;

// Cookie settings
\$CFG->cookiename = 'TSUGI';
\$CFG->cookiepad = '196896';

// Mail settings
\$CFG->maildomain = false;
\$CFG->maileol = "\n";

// LTI settings
\$CFG->launchactivity = 100;
\$CFG->eventcheck = true;

// Bootswatch theme (cerulean, cosmo, cyborg, darkly, flatly, journal,
// litera, lumen, lux, materia, minty, morph, pulse, quartz, sandstone,
// simplex, sketchy, slate, solar, spacelab, superhero, united, vapor, yeti, zephyr)
\$CFG->bootswatch = false;
\$CFG->bootswatch_color = false;

// Maintenance mode
\$CFG->upgrading = false;

// SSL verification (set to false for development only)
\$CFG->verifypeer = true;

// Memcache/Memcached (optional - for session storage)
// \$CFG->memcache = 'tcp://localhost:11211';
// \$CFG->memcached = 'localhost:11211';
EOPHP

        chown www-data:www-data "$CONFIG_FILE"
        chmod 640 "$CONFIG_FILE"
        echo "config.php generated successfully!"
    else
        echo "config.php already exists, skipping generation."
    fi
}

# =============================================================================
# Database Schema Setup
# =============================================================================

setup_database_schema() {
    echo "Setting up Tsugi database schema..."

    # Check if tables already exist
    TABLE_COUNT=$(mysql -u root -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${TSUGI_DB_NAME}'" 2>/dev/null || echo "0")

    if [ "$TABLE_COUNT" -lt "5" ]; then
        echo "Running Tsugi database upgrade..."
        cd /var/www/html/tsugi/admin
        php upgrade.php
        echo "Database schema created successfully!"
    else
        echo "Database tables already exist, skipping schema creation."
    fi
}

# =============================================================================
# Main Execution
# =============================================================================

case "$1" in
    apache)
        # Initialize MariaDB
        initialize_mariadb

        # Configure Tsugi
        configure_tsugi

        # Setup database schema
        setup_database_schema

        echo "=============================================="
        echo "Tsugi is ready!"
        echo ""
        echo "Access Tsugi at: ${TSUGI_WWWROOT}"
        echo "Admin password: ${TSUGI_ADMIN_PASSWORD}"
        echo ""
        echo "First time setup:"
        echo "1. Navigate to Admin (click Admin link)"
        echo "2. Enter the admin password to create tables"
        echo "3. Start using Tsugi!"
        echo "=============================================="

        # Start Apache in foreground
        exec apache2ctl -D FOREGROUND
        ;;

    mariadb)
        # Only start MariaDB
        initialize_mariadb
        echo "MariaDB is running..."
        # Keep container running
        tail -f /dev/null
        ;;

    bash|sh)
        # Interactive shell
        exec /bin/bash
        ;;

    *)
        # Execute custom command
        exec "$@"
        ;;
esac
